name: Publish Docker image

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Build docker-image
        run: docker build -t stakkes/frontend-js .
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: push
        run: docker push stakkes/frontend-js:latest

      - name: Create Release
          uses: actions/create-release@latest
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              tag_name: ${{ github.ref }}
              release_name: Release ${{ github.ref }}
              body: |
                ${{ steps.Changelog.outputs.changelog }}
              draft: false
              prerelease: false