name: Publish Docker image

on:
  push:
    branches:
      - "master"
      - "dev"
  pull_request:
    branches:
      - "master"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Build docker-image
        run: docker build . --tag ghcr.io/stakkes/frontend-js:latest
      - name: log in to github
        run: echo ${{ SECRET_GITHUB_PASSWORD }} | docker login ghcr.io -u ${{ SECRET_GITHUB_USERNAME }} --password-stdin
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: push
        run: docker push ghcr.io/stakkes/frontend-js:latest   
      - name: webhook
        run: curl -X POST ${{ secrets.WEBHOOK_URL }}

  