name: Publish Docker image

on:
  push:
    branches:
      - "master"
      - "dev"
  pull_request:
    branches:
      - "master"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Build docker-image
        run: docker build -t stakkes/frontend-js .
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: push
        run: docker push stakkes/frontend-js:latest
  webhook:
  uses: distributhor/workflow-webhook@v2
      env:
        webhook_url: ${{ secrets.WEBHOOK_URL }}

  